site:
  title: Installation of Red Hat OpenStack Platform 16.2
  start_page: rhosp-install-16.2::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
